<?php

/**
 * @file
 * Contains the event_depublish module.
 */

/**
 * Implements hook_cron().
 */
function event_depublish_cron(): void {
  $queue = \Drupal::queue('depublish_expired_events');
  $query = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'event')
    ->condition('field_date_range.end_value', date('Y-m-d'), '<')
    ->accessCheck(TRUE);
  $nids = $query->execute();

  foreach ($nids as $nid) {
    $queue->createItem(['nid' => $nid]);
  }

}
